#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#
# To edit the 'php-fpm' base Image, visit its repository on Github
#    https://github.com/Laradock/php-fpm
#
# To change its version, see the available Tags on the Docker Hub:
#    https://hub.docker.com/r/laradock/php-fpm/tags/
#
# Note: Base Image name format {image-tag}-{php-version}
#

ARG PHP_VERSION=${PHP_VERSION}

FROM laradock/php-fpm:2.2-${PHP_VERSION}

LABEL maintainer="T301000 <t301000@gmail.com>"

#
#--------------------------------------------------------------------------
# Mandatory Software's Installation
#--------------------------------------------------------------------------
#
# Mandatory Software's such as ("mcrypt", "pdo_mysql", "libssl-dev", ....)
# are installed on the base image 'laradock/php-fpm' image. If you want
# to add more Software's or remove existing one, you need to edit the
# base image (https://github.com/Laradock/php-fpm).
#

#
#--------------------------------------------------------------------------
# Optional Software's Installation
#--------------------------------------------------------------------------
#
# Optional Software's will only be installed if you set them to `true`
# in the `docker-compose.yml` before the build.
# Example:
#   - INSTALL_ZIP_ARCHIVE=true
#

###########################################################################
# SOAP:
###########################################################################

RUN rm /etc/apt/preferences.d/no-debian-php && \
    apt-get update -yqq && \
    apt-get -y install libxml2-dev php-soap && \
    docker-php-ext-install soap

###########################################################################
# pgsql
###########################################################################

###########################################################################
# pgsql client
###########################################################################

###########################################################################
# xDebug:
###########################################################################

###########################################################################
# Blackfire:
###########################################################################

###########################################################################
# PHP REDIS EXTENSION
###########################################################################

RUN printf "\n" | pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis

###########################################################################
# Swoole EXTENSION
###########################################################################

###########################################################################
# MongoDB:
###########################################################################

###########################################################################
# AMQP:
###########################################################################

###########################################################################
# ZipArchive:
###########################################################################

RUN docker-php-ext-install zip

###########################################################################
# bcmath:
###########################################################################

RUN docker-php-ext-install bcmath

###########################################################################
# GMP (GNU Multiple Precision):
###########################################################################

###########################################################################
# PHP Memcached:
###########################################################################

RUN curl -L -o /tmp/memcached.tar.gz "https://github.com/php-memcached-dev/php-memcached/archive/php7.tar.gz" \
    && mkdir -p memcached \
    && tar -C memcached -zxvf /tmp/memcached.tar.gz --strip 1 \
    && ( \
        cd memcached \
        && phpize \
        && ./configure \
        && make -j$(nproc) \
        && make install \
    ) \
    && rm -r memcached \
    && rm /tmp/memcached.tar.gz \
    && docker-php-ext-enable memcached

###########################################################################
# Exif:
###########################################################################

RUN docker-php-ext-install exif

###########################################################################
# PHP Aerospike:
###########################################################################

###########################################################################
# Opcache:
###########################################################################

RUN docker-php-ext-install opcache

# Copy opcache configration
COPY ./opcache.ini /usr/local/etc/php/conf.d/opcache.ini

###########################################################################
# Mysqli Modifications:
###########################################################################

RUN docker-php-ext-install mysqli

###########################################################################
# Tokenizer Modifications:
###########################################################################

RUN docker-php-ext-install tokenizer

###########################################################################
# Human Language and Character Encoding Support:
###########################################################################

#RUN apt-get update -yqq && \
RUN apt-get install -y zlib1g-dev libicu-dev g++ && \
    docker-php-ext-configure intl && \
    docker-php-ext-install intl

###########################################################################
# GHOSTSCRIPT:
###########################################################################

RUN apt-get install -y \
    poppler-utils \
    ghostscript 

###########################################################################
# LDAP:
###########################################################################

###########################################################################
# SQL SERVER:
###########################################################################

###########################################################################
# Image optimizers:
###########################################################################

USER root

RUN apt-get install -y --force-yes jpegoptim optipng pngquant gifsicle

###########################################################################
# ImageMagick:
###########################################################################

#USER root

RUN apt-get install -y libmagickwand-dev imagemagick && \
    pecl install imagick && \
    docker-php-ext-enable imagick

###########################################################################
# IMAP:
###########################################################################

###########################################################################
# 新增 => XSL:
###########################################################################

RUN apt install -y libxslt1.1 libxslt1-dev && docker-php-ext-install xsl

###########################################################################
# Check PHP version:
###########################################################################

ARG PHP_VERSION=${PHP_VERSION}

RUN php -v | head -n 1 | grep -q "PHP ${PHP_VERSION}."

#
#--------------------------------------------------------------------------
# Final Touch
#--------------------------------------------------------------------------
#

#COPY ./laravel.ini /usr/local/etc/php/conf.d
#COPY ./xlaravel.pool.conf /usr/local/etc/php-fpm.d/

#USER root

# Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    rm /var/log/lastlog /var/log/faillog

RUN usermod -u 1000 www-data

WORKDIR /var/www

CMD ["php-fpm"]

EXPOSE 9000
